name: SensitiveWordFilter
main: xyz.moeluoyu.sensitivewordfilter.Main
version: 1.1
description: 敏感词检测系统
commands:
  sensitivewordfilter:
    description: SensitiveWordFilter主命令.
    aliases: [swf]
    permission: sensitivewordfilter.setfiltermode
