name: SensitiveWordFilter
main: xyz.moeluoyu.sensitivewordfilter.SensitiveWordFilter
version: 1.3
description: 敏感词检测系统
commands:
  sensitivewordfilter:
    description: SensitiveWordFilter主命令.
    aliases: [swf]
    permission: sensitivewordfilter.admin
permissions:
  sensitivewordfilter.admin:
    description: 插件管理员权限
    default: op
